-- Unable to render VIEW DDL for object RDW.HUBE_EHCONDL_ISUR_EVER with DBMS_METADATA attempting internal generator.
CREATE VIEW RDW.HUBE_EHCONDL_ISUR_EVER
AS
SELECT CAST(STANDARD_HASH(CONTRACT_DELIVERY_BID || CHR(31) || BRAND_REF_BID, 'MD5') AS VARCHAR2(32 CHAR)) AS VW_H_CONTRACT_DELIVERY_HK
	,CAST('ISUR_EVER' AS VARCHAR2(200 CHAR)) AS VW_RECORD_SOURCE
	,CAST(SEQ_ID AS NUMBER) AS VW_SEQ_ID
	,CAST(LOAD_DTS_START AS DATE) AS VW_LOAD_DTS_START
	,CAST(LOAD_DTS_END AS DATE) AS VW_LOAD_DTS_END
	,CAST(PREV_LOAD_DTS_START AS DATE) AS VW_PREV_LOAD_DTS_START
	,CAST(PREV_LOAD_DTS_END AS DATE) AS VW_PREV_LOAD_DTS_END
	,CAST(CASE 
			WHEN CONTRACT_DELIVERY_BID IS NULL
				OR BRAND_REF_BID IS NULL
				THEN RTRIM(LTRIM(NVL2(CONTRACT_DELIVERY_BID, NULL, 'CONTRACT_DELIVERY_BID') || ',' || NVL2(BRAND_REF_BID, NULL, 'BRAND_REF_BID'), ','), ',')
			END AS VARCHAR2(500 CHAR)) VW_REJECT_REASON
	,CAST(CONTRACT_DELIVERY_BID AS VARCHAR2(50 CHAR)) CONTRACT_DELIVERY_BID
	,CAST(BRAND_REF_BID AS VARCHAR2(5 CHAR)) BRAND_REF_BID
FROM (
	SELECT SEQ_ID
		,REVER.VERTRAG CONTRACT_DELIVERY_BID
		,BRAND_BID.INTERNAL_CD BRAND_REF_BID
		,REVER.LOAD_DTS_START
		,REVER.LOAD_DTS_END
		,PREV_LOAD_DTS_START
		,PREV_LOAD_DTS_END
	FROM RDW.ISUR_EVER REVER
	JOIN (
		SELECT RANK() OVER (
				ORDER BY WF_RUN_ID DESC
				) RNK
			,PREV_SEQ_ID
			,PREV_LOAD_DTS_START
			,PREV_LOAD_DTS_END
		FROM RDW.ETL_RUN_DELTA_POINTER
		WHERE WF_NAME = 'wf_HUBE_CONTRACT_DELIVERY_ISU_for_ISUR_EVER'
			AND MAPPING_NAME = 'm_HUBE_CONTRACT_DELIVERY_ISU_for_ISUR_EVER'
		) GERDPR ON GERDPR.RNK = 1
	LEFT OUTER JOIN RDW.REF_CODE_UNITY BRAND_BID ON BRAND_BID.CODE_GROUP = 'BRAND_BID'
		AND BRAND_BID.SOURCE_SYSTEM = 'SAPGF'
		AND BRAND_BID.EXTERNAL_CD = REVER.MANDT
	WHERE (
			LEAST(REVER.LOAD_DTS_END, BRAND_BID.END_DTS) = TO_DATE('99991231', 'YYYYMMDD')
			AND REVER.SEQ_ID > GERDPR.PREV_SEQ_ID
			OR LEAST(REVER.LOAD_DTS_END, BRAND_BID.END_DTS) < TO_DATE('99991231', 'YYYYMMDD')
			AND LEAST(REVER.LOAD_DTS_END, BRAND_BID.END_DTS) > GERDPR.PREV_LOAD_DTS_END
			)
	) a
